# Generated by Django 3.2.23 on 2023-12-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='fuel_capacity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
