# Generated by Django 3.2.23 on 2023-12-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0002_airplane_fuel_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='fuel_consumption',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='fuel_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='passenger',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
