# Generated by Django 3.2.23 on 2023-12-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0003_auto_20231222_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='fuel_capacity',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='fuel_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
