# Generated by Django 3.2.23 on 2023-12-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0004_auto_20231222_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='flight_endurance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='fuel_capacity',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='fuel_consumption',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
