# Generated by Django 3.2.23 on 2023-12-25 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0006_rename_id_airplane_airplane_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='airplane_id',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='passenger',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
